language: php
php:
  - '7.1'
  - '7.2'
services: mysql
addons:
  hosts:
    - db
before_install:
  - mysql -u root -e "CREATE USER 'app'@'%' IDENTIFIED BY 'secret'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'app'@'%'"
  - mysql -u root -e "FLUSH PRIVILEGES"
  - mysql -u root -e 'CREATE DATABASE `beers_tests`'
install: 
  - composer install --prefer-dist
  - tests/bin/yii migrate --interactive=0
script: vendor/bin/codecept run
