version: '3'
services:
  php:
    image: dmstr/php-yii2:7.1-fpm-3.2-nginx
    depends_on:
      - db
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/01-init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
    ports:
      - "5306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: beers
      MYSQL_USER: app
      MYSQL_PASSWORD: secret

volumes:
    db_data: